/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.6 at Tue Jul 14 20:36:51 2020. */

#include "accessories.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Response_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Response, error_code, error_code, 0),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , OTHER, Response, firmware_component, error_code, &FirmwareComponent_fields),
    PB_ONEOF_FIELD(payload,   3, MESSAGE , ONEOF, STATIC  , UNION, Response, device_information, error_code, &DeviceInformation_fields),
    PB_ONEOF_FIELD(payload,  28, MESSAGE , ONEOF, STATIC  , UNION, Response, device_features, error_code, &DeviceFeatures_fields),
    PB_LAST_FIELD
};

const pb_field_t ControlEnvelope_fields[7] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ControlEnvelope, command, command, 0),
    PB_ONEOF_FIELD(payload,   9, MESSAGE , ONEOF, STATIC  , OTHER, ControlEnvelope, response, command, &Response_fields),
    PB_ONEOF_FIELD(payload,  20, MESSAGE , ONEOF, STATIC  , UNION, ControlEnvelope, get_device_information, command, &GetDeviceInformation_fields),
    PB_ONEOF_FIELD(payload,  28, MESSAGE , ONEOF, STATIC  , UNION, ControlEnvelope, get_device_features, command, &GetDeviceFeatures_fields),
    PB_ONEOF_FIELD(payload,  94, MESSAGE , ONEOF, STATIC  , UNION, ControlEnvelope, update_component_segment, command, &UpdateComponentSegment_fields),
    PB_ONEOF_FIELD(payload,  95, MESSAGE , ONEOF, STATIC  , UNION, ControlEnvelope, apply_firmware, command, &ApplyFirmware_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Response, payload.firmware_component) < 65536 && pb_membersize(Response, payload.device_information) < 65536 && pb_membersize(Response, payload.device_features) < 65536 && pb_membersize(ControlEnvelope, payload.response) < 65536 && pb_membersize(ControlEnvelope, payload.get_device_information) < 65536 && pb_membersize(ControlEnvelope, payload.get_device_features) < 65536 && pb_membersize(ControlEnvelope, payload.update_component_segment) < 65536 && pb_membersize(ControlEnvelope, payload.apply_firmware) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Response_ControlEnvelope)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Response, payload.firmware_component) < 256 && pb_membersize(Response, payload.device_information) < 256 && pb_membersize(Response, payload.device_features) < 256 && pb_membersize(ControlEnvelope, payload.response) < 256 && pb_membersize(ControlEnvelope, payload.get_device_information) < 256 && pb_membersize(ControlEnvelope, payload.get_device_features) < 256 && pb_membersize(ControlEnvelope, payload.update_component_segment) < 256 && pb_membersize(ControlEnvelope, payload.apply_firmware) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Response_ControlEnvelope)
#endif


/* @@protoc_insertion_point(eof) */
