/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.6 at Wed Jul 15 00:57:12 2020. */

#include "directiveHeader.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t header_DirectiveHeaderProto_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, header_DirectiveHeaderProto, namespacc, namespacc, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, header_DirectiveHeaderProto, name, namespacc, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, header_DirectiveHeaderProto, messageId, name, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, header_DirectiveHeaderProto, dialogRequestId, messageId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
