/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.6 at Tue Jul 14 20:36:52 2020. */

#include "device.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeviceInformation_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, DeviceInformation, serial_number, serial_number, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, DeviceInformation, name, serial_number, 0),
    PB_FIELD(  3, UENUM   , REPEATED, STATIC  , OTHER, DeviceInformation, supported_transports, name, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, DeviceInformation, device_type, supported_transports, 0),
    PB_LAST_FIELD
};

const pb_field_t GetDeviceInformation_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t DeviceFeatures_fields[3] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, DeviceFeatures, features, features, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, DeviceFeatures, device_attributes, features, 0),
    PB_LAST_FIELD
};

const pb_field_t GetDeviceFeatures_fields[1] = {
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
