/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Tue Jul 14 20:36:52 2020. */

#ifndef PB_DEVICE_PB_H_INCLUDED
#define PB_DEVICE_PB_H_INCLUDED
#include <pb.h>

#include "common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _GetDeviceFeatures {
    char dummy_field;
/* @@protoc_insertion_point(struct:GetDeviceFeatures) */
} GetDeviceFeatures;

typedef struct _GetDeviceInformation {
    char dummy_field;
/* @@protoc_insertion_point(struct:GetDeviceInformation) */
} GetDeviceInformation;

typedef struct _DeviceFeatures {
    uint64_t features;
    uint64_t device_attributes;
/* @@protoc_insertion_point(struct:DeviceFeatures) */
} DeviceFeatures;

typedef struct _DeviceInformation {
    char serial_number[20];
    char name[16];
    pb_size_t supported_transports_count;
    Transport supported_transports[2];
    char device_type[22];
/* @@protoc_insertion_point(struct:DeviceInformation) */
} DeviceInformation;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DeviceInformation_init_default           {"", "", 0, {_Transport_MIN, _Transport_MIN}, ""}
#define GetDeviceInformation_init_default        {0}
#define DeviceFeatures_init_default              {0, 0}
#define GetDeviceFeatures_init_default           {0}
#define DeviceInformation_init_zero              {"", "", 0, {_Transport_MIN, _Transport_MIN}, ""}
#define GetDeviceInformation_init_zero           {0}
#define DeviceFeatures_init_zero                 {0, 0}
#define GetDeviceFeatures_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceFeatures_features_tag              1
#define DeviceFeatures_device_attributes_tag     2
#define DeviceInformation_serial_number_tag      1
#define DeviceInformation_name_tag               2
#define DeviceInformation_supported_transports_tag 3
#define DeviceInformation_device_type_tag        4

/* Struct field encoding specification for nanopb */
extern const pb_field_t DeviceInformation_fields[5];
extern const pb_field_t GetDeviceInformation_fields[1];
extern const pb_field_t DeviceFeatures_fields[3];
extern const pb_field_t GetDeviceFeatures_fields[1];

/* Maximum encoded size of messages (where known) */
#define DeviceInformation_size                   68
#define GetDeviceInformation_size                0
#define DeviceFeatures_size                      22
#define GetDeviceFeatures_size                   0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEVICE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
