/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.6 at Tue Jul 14 20:36:52 2020. */

#include "firmware.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FirmwareComponent_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, FirmwareComponent, version, version, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, FirmwareComponent, name, version, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, FirmwareComponent, size, name, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, FirmwareComponent, signature, size, 0),
    PB_LAST_FIELD
};

const pb_field_t FirmwareInformation_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, FirmwareInformation, version, version, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInformation, name, version, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, FirmwareInformation, components, name, &FirmwareComponent_fields),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInformation, locale, components, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInformation, version_name, locale, 0),
    PB_LAST_FIELD
};

const pb_field_t UpdateComponentSegment_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, UpdateComponentSegment, component_name, component_name, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, UpdateComponentSegment, component_offset, component_name, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, UpdateComponentSegment, segment_size, component_offset, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, UpdateComponentSegment, segment_signature, segment_size, 0),
    PB_LAST_FIELD
};

const pb_field_t ApplyFirmware_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ApplyFirmware, firmware_information, firmware_information, &FirmwareInformation_fields),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ApplyFirmware, restart_required, firmware_information, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FirmwareInformation, components[0]) < 65536 && pb_membersize(ApplyFirmware, firmware_information) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_FirmwareComponent_FirmwareInformation_UpdateComponentSegment_ApplyFirmware)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FirmwareInformation, components[0]) < 256 && pb_membersize(ApplyFirmware, firmware_information) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_FirmwareComponent_FirmwareInformation_UpdateComponentSegment_ApplyFirmware)
#endif


/* @@protoc_insertion_point(eof) */
